#!/usr/bin/env bash
# comment

if [ "$#" -eq 1 ]
then
	dig www."$1" | grep -A1 'ANSWER SECTION:' | grep -e 'www' | awk '{printf "The subdomain www is a " $4 " record and points to " $5"\n"}'
	dig lb-01."$1" | grep -A1 'ANSWER SECTION:' | grep -e 'lb-01' | awk '{printf "The subdomain lb-01 is a " $4 " record and points to " $5"\n"}'
	dig web-01."$1" | grep -A1 'ANSWER SECTION:' | grep -e 'web-01' | awk '{printf "The subdomain web-01 is a " $4 " record and points to " $5"\n"}'
	dig web-02."$1" | grep -A1 'ANSWER SECTION:' | grep -e 'web-02' | awk '{printf "The subdomain web-02 is a " $4 " record and points to " $5"\n"}'
elif [ "$#" -eq 2 ]
then
	dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | grep -e "$2" | awk '{printf "The subdomain '$2' is a " $4 " record and points to " $5"\n"}'
fi
