#!/usr/bin/env bash
# comment
sudo apt-get -y update
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.7
sudo apt-get -y update
sudo apt-get install -y haproxy=1.7.\*
sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy
sudo sed -i '40i\listen appname 0.0.0.0:80\n\tbalance roundrobin\n\tmode http\n\tserver 224-web-01 34.230.90.165:80 check\n\tserver 224-web-02 54.243.17.82:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy start
