#!/usr/bin/env bash
# why doesnt this work?
sudo apt-get -y update
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get install -y haproxy=1.8.\*
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
echo -e "\nfrontend haproxynode\n\tbind *:80\n\tmode http\n\tdefault_backend backendnodes\n\nbackend backendnodes\n\tbalance roundrobin\n\toption forwardfor\n\thttp-request set-header X-Forwarded-Port %[dst_port]\n\thttp-request add-header X-Forwarded-Proto https if { ssl_fc }\n\tserver 224-web-01 34.230.90.165:80 check\n\tserver 224-web-02 54.243.17.82:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service rsyslog start
sudo service haproxy start
