#!/usr/bin/env bash
# why doesnt this work?
sudo apt-get -y update
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get install -y haproxy=1.8.\*
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
echo -e "\nlisten appname 0.0.0.0:80\n\tbind 0:80\n\tbalance roundrobin\n\tmode http\n\tserver 224-web-01 34.230.90.165:80 check\n\tserver 224-web-02 54.243.17.82:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
service rsyslog start
sudo service haproxy start
sudo service nginx start
