#!/usr/bin/env bash
# fizzbuzz, 1 to 100
#!/bin/bash
(( i=1 ));
while (( i <= 100 )); 
do
	if { ( (( i % 5 == 0 )) && (( i % 3 == 0 )) ) } then echo "fizzbuzz";
	elif (( i % 5 == 0 )); then echo "buzz";
	elif (( i % 3 == 0 )); then echo "fizz";
	else
		echo "$i";
	fi
(( i++ ))
done
