#!/usr/bin/env bash
# Script displays Holberton School 10 times, Hi on 9th iteration
COUNTER=1
	while [ $COUNTER -lt 11 ]; do
		
		echo 'Holberton School'
		if (( COUNTER == 9 )); then
			echo 'Hi'
		fi
		let COUNTER=COUNTER+1 
	done
