#!/usr/bin/env bash
# comment
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '$a 8.8.8.8 facebook.com' ~/hosts.new
#ed ~/hosts.new <<-'EOF'
#	/127.0.0.[0-9]/a
#	8.8.8.8 facebook.com
#	.
#	wq
#EOF
cp -f ~/hosts.new /etc/hosts
