#!/usr/bin/env bash
# comment
pkill apache2
sudo service nginx stop
chmod -R 777 /etc/nginx/nginx.conf
sudo sed -i 's/listen 80 default_server/listen 8080 default_server/g' /etc/nginx/sites-available/default
sudo sed -i 's/listen [::]:80 default_server ipv6only=on/listen [::]:8080 default_server ipv6only=on/g' /etc/nginx/sites-available/default
sudo sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
service nginx restart
