#!/usr/bin/env bash
# comment
pkill apache2
sudo service apache2 stop
chmod -R 777 /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo sed -i "s/#user www-data/user nginx/" etc/nginx/nginx.conf
sudo -u nginx service nginx restart
